# Generated by Django 5.0.6 on 2024-06-24 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaFlavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='', max_length=50)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.pizzaflavour')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSizePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medium_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_large_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.pizzaflavour')),
            ],
        ),
    ]
